version: "3.9"
services:

  aabrham:
    container_name: aabrham
    build: .
    depends_on:
      - redis
    ports:
      - "18080:18080"

  redis:
    container_name: redis
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
